stages:
  - test
  - deploy

test-job:
  stage: test
  rules:
    - when: on_success
  script:
    - npm i
    - npm run build
deploy-job:
  stage: deploy
  script:
    - cp -r . /chessjs/client/
    - cd /chessjs/client/
    - npm i
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never

